import OpenAI from "openai"

export const CASE_SUMMARY_MODEL = "qwen3.7-plus-2026-05-26"
const sections = { initial: ["initial_status", "treatment_actions", "follow_up_focus"], ongoing: ["initial_status", "treatment_actions", "key_changes", "current_status", "follow_up_focus"], completed: ["initial_status", "treatment_actions", "key_changes", "final_outcome", "completion_summary", "post_treatment_follow_up"] }
const prompt = `Generate a Chinese orthodontic case-summary candidate only from supplied doctor-confirmed facts. Do not add diagnoses, outcomes, recommendations, or unsupported facts. Every non-empty fact needs existing source_timepoint_ids. Absence is neither persistence nor improvement. current_status/final_outcome need explicit recent support; cross-time changes need earlier and later evidence. Completion itself never implies post-treatment follow-up. Fixed-key arrays may be empty. Timeline is input order and only describes its own timepoint. Return strict JSON only.`
const fact = (ids, change = false) => ({ type: "object", additionalProperties: false, properties: { content: { type: "string" }, source_timepoint_ids: { type: "array", minItems: change ? 2 : 1, items: { type: "string", enum: ids } } }, required: ["content", "source_timepoint_ids"] })
function schemaFor(mode, ids) { const properties = { case_overview: fact(ids), treatment_timeline: { type: "array", items: { type: "object", additionalProperties: false, properties: { timepoint_id: { type: "string", enum: ids }, captured_on: { type: "string" }, stage: { type: "string", enum: ["initial", "ongoing", "completed"] }, content: { type: "string" }, source_timepoint_ids: { type: "array", minItems: 1, items: { type: "string", enum: ids } } }, required: ["timepoint_id", "captured_on", "stage", "content", "source_timepoint_ids"] } } }; for (const key of sections[mode]) properties[key] = { type: "array", items: fact(ids, key === "key_changes") }; return { type: "object", additionalProperties: false, properties, required: Object.keys(properties) } }
function adapt(input) { return { case_id: input.case_id, summary_mode: input.summary_mode, timepoints: input.timepoints.map((timepoint) => ({ id: timepoint.timepoint_id, captured_on: timepoint.captured_on ?? "", stage: input.summary_mode, confirmed_segments: [{ content: timepoint.confirmed_text }] })) } }
function normalize(value, mode) { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const keys = ["case_overview", "treatment_timeline", ...sections[mode]]; if (Object.keys(value).length !== keys.length || keys.some((key) => !(key in value))) return null; return { summary_mode: mode, case_overview: value.case_overview, treatment_timeline: value.treatment_timeline, sections: sections[mode].map((key) => ({ key, items: value[key] })) } }
function validate(value, input) { const errors = [], normalized = normalize(value, input.summary_mode), byId = new Map(input.timepoints.map((x) => [x.id, x])), factCheck = (x) => { if (!x || typeof x.content !== "string" || !Array.isArray(x.source_timepoint_ids) || !x.source_timepoint_ids.length) errors.push("schema"); else x.source_timepoint_ids.forEach((id) => { if (!byId.has(id)) errors.push("provenance") }) }; if (!normalized) return { errors: ["schema"], normalized: null }; factCheck(normalized.case_overview); let previous = ""; for (const item of normalized.treatment_timeline) { const source = byId.get(item?.timepoint_id); if (!source || item.captured_on !== source.captured_on || item.stage !== source.stage || !item.source_timepoint_ids?.includes(item.timepoint_id)) errors.push("timeline_provenance"); if (previous && item.captured_on < previous) errors.push("timeline_order"); previous = item.captured_on; factCheck(item) } const timelineIds = new Set(normalized.treatment_timeline.map((item) => item?.timepoint_id)); if (input.timepoints.some((timepoint) => !timelineIds.has(timepoint.id))) errors.push("timeline_completeness"); for (const section of normalized.sections) for (const item of section.items) { factCheck(item); if (section.key === "key_changes" && new Set(item.source_timepoint_ids ?? []).size < 2) errors.push("change_sources"); if (section.key === "final_outcome" && !item.source_timepoint_ids?.some((id) => byId.get(id)?.stage === "completed")) errors.push("final_source") } return { errors: [...new Set(errors)], normalized } }

export async function generateCaseSummary(input) {
  if (!input.timepoints.length) return { input, raw_model_output: null, parsed_summary_json: null, automatic_contract_checks: null, error: "no_effective_confirmed_timepoints" }
  if (!process.env.DASHSCOPE_API_KEY || !process.env.DASHSCOPE_BASE_URL) return { input, raw_model_output: null, parsed_summary_json: null, automatic_contract_checks: null, error: "DASHSCOPE_API_KEY and DASHSCOPE_BASE_URL are required" }
  const adapted = adapt(input), client = new OpenAI({ apiKey: process.env.DASHSCOPE_API_KEY, baseURL: process.env.DASHSCOPE_BASE_URL, timeout: 180000, maxRetries: 0 })
  const providerStartedAt = performance.now()
  try {
    const response = await client.chat.completions.create({ model: CASE_SUMMARY_MODEL, messages: [{ role: "system", content: prompt }, { role: "user", content: JSON.stringify({ case_id: adapted.case_id, timepoints: adapted.timepoints }) }], response_format: { type: "json_schema", json_schema: { name: `case_summary_${adapted.summary_mode}_v1`, strict: true, schema: schemaFor(adapted.summary_mode, adapted.timepoints.map((timepoint) => timepoint.id)) } } })
    const provider_ms = Math.round(performance.now() - providerStartedAt), validationStartedAt = performance.now()
    const raw = response.choices?.[0]?.message?.content
    if (!raw) throw new Error("empty_model_response")
    const parsed = JSON.parse(raw), errors = validate(parsed, adapted).errors, checks = { json_parse: true, strict_schema: !errors.includes("schema"), mode_contract: !errors.includes("schema"), provenance: !errors.some((error) => error.includes("provenance") || error === "final_source"), timeline: !errors.includes("timeline_order"), timeline_completeness: !errors.includes("timeline_completeness"), overall: errors.length === 0 }
    return { input, raw_model_output: raw, parsed_summary_json: parsed, automatic_contract_checks: checks, error: errors.length ? errors.join("|") : null, retry_count: 0, provider_call_count: 1, provider_ms, validation_ms: Math.round(performance.now() - validationStartedAt) }
  } catch (error) {
    return { input, raw_model_output: null, parsed_summary_json: null, automatic_contract_checks: { json_parse: false, strict_schema: false, mode_contract: false, provenance: false, timeline: false, timeline_completeness: false, overall: false }, error: error instanceof Error ? error.message : String(error), retry_count: 0, provider_call_count: 1, provider_ms: Math.round(performance.now() - providerStartedAt), validation_ms: 0 }
  }
}
