import { readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const EVAL_ROOT = path.join(ROOT, "data", "eval", "case_summary_v1")
const readJson = async (file) => JSON.parse(await readFile(file, "utf8"))
const esc = (value) => String(value ?? "").replaceAll("|", "\\|").replaceAll("\n", "<br>")
function facts(value) { if (!value?.length) return "（空）"; return value.map((item) => `- ${item.content}\n  - provenance: ${item.source_timepoint_ids.join(", ")}`).join("\n") }
function summary(value, mode) { if (!value) return "模型未返回可解析 summary。"; const keys = { initial: ["initial_status", "treatment_actions", "follow_up_focus"], ongoing: ["initial_status", "treatment_actions", "key_changes", "current_status", "follow_up_focus"], completed: ["initial_status", "treatment_actions", "key_changes", "final_outcome", "completion_summary", "post_treatment_follow_up"] }[mode]; return [`### Case overview\n${facts([value.case_overview])}`, `### Treatment timeline\n${facts(value.treatment_timeline.map((item) => ({ content: `[${item.timepoint_id}; ${item.captured_on}; ${item.stage}] ${item.content}`, source_timepoint_ids: item.source_timepoint_ids })))}`, ...keys.map((key) => `### ${key}\n${facts(value[key])}`)].join("\n\n") }
async function main() { const expectations = await readJson(path.join(EVAL_ROOT, "semantic_expectations.json")), scorecard = await readJson(path.join(EVAL_ROOT, "semantic_scorecard.json")), run = await readJson(path.join(EVAL_ROOT, "run_summary.json")); const runById = new Map(run.cases.map((item) => [item.case_id, item])); const lines = ["# Case Summary Semantic Review Packet", "", "人工 Semantic Eval 使用。此文档不包含自动 Semantic 判定。", "", "## 评分栏", "", ...scorecard.scoring.map((score) => `- ${score.id} ${score.name}：未评分`), ""]; for (let number = 1; number <= 6; number += 1) { const id = `eval_case_${String(number).padStart(2, "0")}`, input = await readJson(path.join(EVAL_ROOT, "inputs", `${id}.json`)), output = await readJson(path.join(EVAL_ROOT, "outputs", `${id}.json`)), expectation = expectations.cases.find((item) => item.case_id === id), automatic = runById.get(id); lines.push(`## ${id}`, "", `**summary_mode:** ${input.summary_mode}`, "", "### 原始 confirmed timepoints", ""); for (const point of input.timepoints) lines.push(`- ${point.timepoint_id}（sequence_order: ${point.sequence_order}）：${point.confirmed_text}`); lines.push("", "### Parsed AI summary", "", summary(output.parsed_summary_json, input.summary_mode), "", "### AI source_timepoint_ids / provenance", ""); if (!output.parsed_summary_json) lines.push("（无可解析 AI summary）"); else { const entries = [output.parsed_summary_json.case_overview, ...output.parsed_summary_json.treatment_timeline, ...Object.values(output.parsed_summary_json).filter(Array.isArray).flat()]; lines.push([...new Set(entries.flatMap((entry) => entry.source_timepoint_ids ?? []))].map((source) => `- ${source}`).join("\n") || "（无）") } lines.push("", "### Semantic expectations", "", "**must_include**", ...expectation.must_include.map((item) => `- ${item}`), "", "**must_not_claim**", ...expectation.must_not_claim.map((item) => `- ${item}`), "", "### Automatic Contract", "", "| Provider | JSON parse | Strict schema | Mode contract | Provenance | Timeline | Overall | Failure reason |", "|---|---|---|---|---|---|---|---|", `| ${automatic.provider_success ? "PASS" : "FAIL"} | ${automatic.json_parse ? "PASS" : "FAIL"} | ${automatic.strict_schema ? "PASS" : "FAIL"} | ${automatic.mode_contract ? "PASS" : "FAIL"} | ${automatic.provenance ? "PASS" : "FAIL"} | ${automatic.timeline ? "PASS" : "FAIL"} | ${automatic.overall ? "PASS" : "FAIL"} | ${esc(automatic.error ?? "—")} |`, "", "### 人工评分", "", "- S1 事实忠实度：未评分", "- S2 时间线正确：未评分", "- S3 状态正确：未评分", "- S4 核心事实覆盖：未评分", "- S5 医学边界：未评分", "") } await writeFile(path.join(EVAL_ROOT, "semantic_review.md"), lines.join("\n"), "utf8") }
await main()
